# 1 Software for modeling

## 1.1 FUNDAMENTALS FOR MODELING SOFTWARE

## 1.2 TYPES OF MODELS

-   DESCRIPTIVE MODELS
-   INFERENTIAL MODELS
-   PREDICTIVE MODELS

## 1.3 CONNECTIONS BETWEEN TYPES OF MODELS

## 1.4 SOME TERMINOLOGY

-   Supervised
    -   Have an outcome variable
    -   Linear regression, neural networks, and numerous other methodologies
    -   Two main sub-categories
        -   *Regression* predicts a numeric outcome
        -   *Classification* predicts an outcome that is an ordered or unordered set of qualitative values
-   Unsupervised
    -   Learn patterns, clusters, or other characteristics of the data but lack an outcome (a dependent variable)
    -   Principal component analysis (PCA), clustering, and autoencoders
    -   Used to understand relationships between variables or sets of variables without an explicit relationship between predictors and an outcome
-   Predictors or Outcomes
    -   Quantitative: Numeric
    -   Qualitative: Discrete

## 1.5 HOW DOES MODELING FIT INTO THE DATA ANALYSIS PROCESS?

-   Exploratory Data Analysis

-   Feature Engineering

-   Model Tuning and Selection

-   Model Evaluation

## 1.6 CHAPTER SUMMARY