---
output: 
  html_document: 
    keep_md: yes
---

# 20 Ensembles of Models

```{r}
library(tidyverse)
library(tidymodels)
library(doParallel)
library(stacks)
library(probably)
library(patchwork)
library(applicable)
tidymodels_prefer()

#super speed
cl <- makePSOCKcluster(8)
registerDoParallel(cl)
```

## 20.1 CREATING THE TRAINING SET FOR STACKING

```{r}
load("ch15_Race_Results.RData")
race_results
```

```{r}
concrete_stack <- 
  stacks() %>% 
  add_candidates(race_results)

concrete_stack
```

## 20.2 BLEND THE PREDICTIONS


```{r}
set.seed(2001)
ens <- blend_predictions(concrete_stack)
```

```{r}
autoplot(ens)
```

```{r}
set.seed(2002)
ens <- blend_predictions(concrete_stack, penalty = 10^seq(-2, -0.5, length = 20))
autoplot(ens)
```

```{r}
ens
```

```{r}
autoplot(ens, "weights") +
  geom_text(aes(x = weight + 0.01, label = model), hjust = 0) + 
  theme(legend.position = "none") +
  lims(x = c(-0.01, 0.8))
```

## 20.3 FIT THE MEMBER MODELS

```{r, error = T}
ens <- fit_members(ens)
```

```{r}
ens
```

## 20.4 TEST SET RESULTS

```{r, error = T}
reg_metrics <- metric_set(rmse, rsq)
ens_test_pred <- 
  predict(ens, concrete_test) %>% 
  bind_cols(concrete_test)

ens_test_pred %>% 
  reg_metrics(compressive_strength, .pred)
```

## 20.5 CHAPTER SUMMARY

```{r}
stopCluster(cl)
```
