# 2 A Tidyverse Primer
## 2.1 TIDYVERSE PRINCIPLES
### 2.1.1 DESIGN FOR HUMANS

```{r}
mtcars[order(mtcars$gear, mtcars$mpg), ]
```

```{r}
library(dplyr)
arrange(.data = mtcars, gear, mpg)
```

### 2.1.2 REUSE EXISTING DATA STRUCTURES

```{r}
boot_samp <- rsample::bootstraps(mtcars, times = 3)
boot_samp
class(boot_samp)
boot_samp[[1]][[1]]$data
```

### 2.1.3 DESIGN FOR THE PIPE AND FUNCTIONAL PROGRAMMING

```{r}
small_mtcars <- arrange(mtcars, gear)
small_mtcars <- slice(small_mtcars, 1:10)
# or
small_mtcars <- slice(arrange(mtcars, gear), 1:10)
```

```{r}
small_mtcars <- mtcars %>%
  arrange(gear) %>%
  slice(1:10)
```

```{r}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() + 
  geom_smooth(method = lm)
```

```{r}
n <- nrow(mtcars)
ratios <- rep(NA_real_, n)
for (car in 1:n) {
  ratios[car] <- log(mtcars$mpg[car]/mtcars$wt[car])
}
head(ratios)

#or

ratios <- log(mtcars$mpg/mtcars$wt)
head(ratios)
```

```{r}
compute_log_ratio <- function(mpg, wt, log_base = exp(1)) {
  log(mpg/wt, base = log_base)
}
```

```{r}
library(purrr)
map(head(mtcars$mpg, 3), sqrt)
```

```{r}
map_dbl(head(mtcars$mpg, 3), sqrt)
```

```{r}
log_ratios <- map2_dbl(mtcars$mpg, mtcars$wt, compute_log_ratio)
head(log_ratios)
```

```{r}
map2_dbl(mtcars$mpg, mtcars$wt, ~ log(.x/.y)) %>% 
  head()
```

## 2.2 EXAMPLES OF TIDYVERSE SYNTAX

```{r}
data.frame(`variable 1` = 1:2, two = 3:4)
```

```{r}
df <- data.frame(`variable 1` = 1:2, two = 3:4, check.names = FALSE)
df
```

```{r}
tbbl <- tibble(`variable 1` = 1:2, two = 3:4)
tbbl
```

```{r}
df$tw
```

```{r}
tbbl$tw
```

```{r}
df[, "two"]
```

```{r}
tbbl[, "two"]
```

```{r}
library(tidyverse)
library(lubridate)

filename <- "CTA_-_Ridership_-__L__Station_Entries_-_Daily_Totals.csv.gz"

all_stations <- 
  # Step 1: Read in the data.
  read_csv(filename) %>% 
  # Step 2: filter columns and rename stationname
  dplyr::select(station = stationname, date, rides) %>% 
  # Step 3: Convert the character date field to a date encoding.
  # Also, put the data in units of 1K rides
  mutate(date = mdy(date), rides = rides / 1000) %>% 
  # Step 4: Summarize the multiple records using the maximum.
  group_by(date, station) %>% 
  summarize(rides = max(rides), .groups = "drop")
```

```{r}
all_stations
```

## 2.3 CHAPTER SUMMARY

