# 5 Spending our Data

## 5.1 COMMON METHODS FOR SPLITTING DATA

```{r}
library(tidymodels)
tidymodels_prefer()
data(ames, package = "modeldata")
ames <- ames %>% mutate(Sale_Price = log10(Sale_Price))

# Set the random number stream using `set.seed()` so that the results can be 
# reproduced later. 
set.seed(501)

ames_split <- initial_split(ames, prop = 0.80)
ames_split
```

```{r}
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

dim(ames_train)
dim(ames_test)
```

```{r}
set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

dim(ames_train)
```

# 5.2 WHAT ABOUT A VALIDATION SET?

```{r}
set.seed(52)
# To put 60% into training, 20% in validation, and 20% in testing:
ames_val_split <- initial_validation_split(ames, prop = c(0.6, 0.2))
ames_val_split
```

```{r}
ames_train <- training(ames_val_split)
ames_test <- testing(ames_val_split)
ames_val <- validation(ames_val_split)
```

## 5.3 MULTILEVEL DATA
## 5.4 OTHER CONSIDERATIONS FOR A DATA BUDGET
## 5.5 CHAPTER SUMMARY

```{r}
library(tidymodels)
data(ames)
ames <- ames %>% mutate(Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
```

